debug: false
chrome_driver_url: "http://localhost:9515"
# QQ的账号密码
#登录方式,如果qq号有验证可以先设置为 qr_code 扫描登录后,再设置为 uin_pwd 账号密码登录
login_type: "uin_pwd"
account:
  uin:
  pwd: ""
ett:
  uin: ""
  pwd: ""
  # 冷却时间 单位: 秒
  cooldown: 2
  #api 超时时间 单位: 秒
  timeout:
setu:
  # 色图自动撤回时间 单位: 秒
  recall_time: 60
  # 色图是否保存本地
  whether_to_save_locally: false

# 最高权限管理 高过 群主/管理员
super_admin:
  - 2939599299
# 对bot的称呼
bot_name:
  - "小白"