[package]
name = "RcoBot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = {version = "1",features = ["derive"]}
serde_json = "1"
serde_yaml = "0"

proc_qq = "0.1"
anyhow = "1"

tokio = { version = "1", features = ["full"] }

log = "0"
tracing = "0.1"
tracing-subscriber = "0.3"

rbs = { version = "0.1"}
rbatis = { version = "4.0"}
rbdc-sqlite = { version = "0.1" }

once_cell = "1"

regex = "1"
chrono = "0"
reqwest = {version = "0", features = ["json"]}
hex = "0"
rand = "0"

async-trait = "0"

delay_timer = "0"

thirtyfour = "0"